### ISSUE TITLE
m7s.live/plugin/gb28181/v4 v4.3.6配m7s.live/engine/v4 v4.13.5会存在版本问题

### ISSUE THREAD

**Issue by XianRenn** [Monibuca/plugin-gb28181#100]
\pkg\mod\m7s.live\plugin\ps\v4@v4.0.1\main.go:182:18: tcpConf.Listen undefined (type config.TCP has no field or method Listen)

能不能把插件和引擎的版本对应关系贴一下

**Comment by langhuihui** [comment]
对应关系可以参考https://github.com/langhuihui/monibuca 里面的go.mod

**Comment by XianRenn** [comment]
—━╋う先人
***@***.***




&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Monibuca/plugin-gb28181"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月3日(星期一) 下午3:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Monibuca/plugin-gb28181] m7s.live/plugin/gb28181/v4 v4.3.6配m7s.live/engine/v4 v4.13.5会存在版本问题 (Issue #100)





 
对应关系可以参考https://github.com/langhuihui/monibuca 里面的go.mod
