### ISSUE TITLE
海康使用gb28181国标传输，通过/gb28181/api/list接口获取还是空

### ISSUE THREAD

**Issue by Zss96** [Monibuca/plugin-gb28181#101]
![image](https://github.com/Monibuca/plugin-gb28181/assets/53645562/e1e6f638-aa0f-4b72-b945-1be6e66bd343)

![image](https://github.com/Monibuca/plugin-gb28181/assets/53645562/868eb76e-6e8b-475e-87d1-f304a8e6979e)

**Comment by langhuihui** [comment]
你可以看一下日志，先把日志配置成 debug

**Comment by Zss96** [comment]
> 你可以看一下日志，先把日志配置成 debug

已经是debug模式了，日志文件为空，
配置文件中udpcachesize值设为0或10，都会出现这个错误。删除就可以了，但是/gb28181/api/list获取列表也为空

![image](https://github.com/Monibuca/plugin-gb28181/assets/53645562/27294f15-c398-4482-9d21-78f34d39237e)

**Comment by aohanhongzhi** [comment]
![image](https://github.com/Monibuca/plugin-gb28181/assets/37319319/77244b1a-8677-46f0-a282-be969f37423e)
我这一样，貌似后端没有接收到啥，但是摄像头是连接互联网的，应该问题不大。但是实际上没有联通


服务器测试端口，貌似没啥响应。

![image](https://github.com/Monibuca/plugin-gb28181/assets/37319319/c236f71b-d3c0-4c9e-a344-4f7c1d4a96de)

**Comment by langhuihui** [comment]
配置一下 sipip 和 mediaip
