### ISSUE TITLE
海康使用gb28181国标传输，通过/gb28181/api/list返回的数据怎么没有包含通道编号字段，需要从哪里获取

### ISSUE THREAD

**Issue by Zss96** [Monibuca/plugin-gb28181#102]
![image](https://github.com/Monibuca/plugin-gb28181/assets/53645562/1c3a4fdc-b6fd-45fb-a192-12dace7fd6e9)

**Comment by langhuihui** [comment]
DeviceID就是通道编号

**Comment by Zss96** [comment]
> DeviceID就是通道编号

我还以为这个是设备id呢？
