### ISSUE TITLE
使用GB28181功能插件运行不起来

### ISSUE THREAD

**Issue by gaop921766** [Monibuca/plugin-gb28181#108]
错误日志：

../../../go/pkg/mod/m7s.live/plugin/gb28181/v4@v4.4.4/handle.go:12:2: "m7s.live/engine/v4" imported and not used
../../../go/pkg/mod/m7s.live/plugin/gb28181/v4@v4.4.4/handle.go:283:3: undefined: EmitEvent
../../../go/pkg/mod/m7s.live/plugin/gb28181/v4@v4.4.4/handle.go:346:3: undefined: EmitEvent

go的版本是：go1.20.14 linux/amd64

代码main.go
package main

import (
   "context"
   _ "m7s.live/plugin/gb28181/v4"
   //"m7s.live/engine/v4"
   //_ "m7s.live/plugin/rtmp/v4"
)

func main() {
   engine.Run(context.Background(), "config.yml")
}
请教下，是main.go哪里写的不对吗？
谢谢！！！

**Comment by langhuihui** [comment]
请到 github.com/langhuihui/monibuca 仓库里面找到 go.mod文件，然后把依赖项随同版本号复制到你的项目中的 go.mod 保持版本依赖的正确性

**Comment by gaop921766** [comment]
收到，太感谢了，谢谢，我弄下
