### ISSUE TITLE
GB28181接入常见问题

### ISSUE THREAD

**Issue by dwdcth** [Monibuca/plugin-gb28181#18]
这里记录一下GB28181接入的常见问题

## SIP/2.0 400 Bad request
国标编码不一致，在nvr或者摄像头的国标配置页；外域编码需要配置和Monibuca一致

##  SIP/2.0 487 Request Terminated
国标编码问题，nvr的本机的11-13位国标编码需要为200，并修改摄像机11-13位的为131，Monibuca编码为120
还有可能是nvr配置Monibuca的国标编码和国标域反了

**Comment by dwdcth** [comment]
## 有设备，通道数为0
设备名有中文

**Comment by dwdcth** [comment]
# invite 成功，无法播放
更改h265编码为h264

**Comment by dwdcth** [comment]
# 一直register状态
有可能网络问题，用下级服务和Monibuca不在同一个网段

**Comment by dwdcth** [comment]
# 非标准国标流 not package standard

详细都写到[qq文档了](https://docs.qq.com/doc/DVkpnVlRWalJEeFV6)
解决办法
![image](https://user-images.githubusercontent.com/1883728/116495569-b601be00-a8d5-11eb-864a-dec0e3b6d9bf.png)

或者

`replace github.com/Monibuca/plugin-rtp v1.0.0 => replace github.com/dwdcth/plugin-rtp v1.0.0-fix1`

**Comment by YiuTerran** [comment]
你可以提个PR吧

> # 非标准国标流 not package standard
> 
> 详细都写到[qq文档了](https://docs.qq.com/doc/DVkpnVlRWalJEeFV6) 解决办法 ![image](https://user-images.githubusercontent.com/1883728/116495569-b601be00-a8d5-11eb-864a-dec0e3b6d9bf.png)
> 
> 或者
> 
> `replace github.com/Monibuca/plugin-rtp v1.0.0 => replace github.com/dwdcth/plugin-rtp v1.0.0-fix1`
