### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by liuxjoy** [Monibuca/plugin-gb28181#29]
GB28181互联网视频传输，丢帧乱码，怎么解决。

**Comment by langhuihui** [comment]
如果是因为摄像头网络情况差导致丢包的话，就会出现视频丢帧，这个没有好的解决方法，摄像头并不会有重传等技术

**Comment by Jxrory** [comment]
> 如果是因为摄像头网络情况差导致丢包的话，就会出现视频丢帧，这个没有好的解决方法，摄像头并不会有重传等技术

小白： 一帧数据有数据完整性校验吗？

**Comment by Jxrory** [comment]
> 如果是因为摄像头网络情况差导致丢包的话，就会出现视频丢帧，这个没有好的解决方法，摄像头并不会有重传等技术

小白： 一帧数据有数据完整性校验吗？

**Comment by langhuihui** [comment]
如何校验呢？
