### ISSUE TITLE
请问能否实现rtsp拉流后转成gb28181客户端？

### ISSUE THREAD

**Issue by xiongfeigood** [Monibuca/plugin-gb28181#37]
首先这个项目太棒了，解决了多种视频流的接入问题。但我们有个场景，相机只有rtsp流，请问能否拉流并转成gb28181格式，然后推送给gb28181服务端？

**Comment by langhuihui** [comment]
我想问一下，为什么会有这个需求

**Comment by xiongfeigood** [comment]
现场我们的用于识别的相机，结果要求接入一个gb28181的平台，现场环境无法用nvr，相机只提供了rtsp，无法推送到对方的gb28181平台，所以就有了这个需求。请问能否实现呢？谢谢
