### ISSUE TITLE
向单设备多通道的NVR设备发送invite时出现多个相同CALL-ID的情况

### ISSUE THREAD

**Issue by pggiroro** [Monibuca/plugin-gb28181#40]
间隔时间很短的时间内连续发送多个INVITE，而这些INVITE的CALL-ID可能一样，导致通道丢失，实际有3个通道，而在M7S里只能收到1个或2个通道

**Comment by charlestamz** [comment]
通道丢失是通道视频没有？还是通道注册不上来？

**Comment by charlestamz** [comment]
fixed on [new commits  ](https://github.com/Monibuca/plugin-gb28181/commit/803543fbdfeabd91edca7999393de04ea6d5069a)
