### ISSUE TITLE
time.After mem++

### ISSUE THREAD

**Issue by wulalawulala** [Monibuca/plugin-gb28181#51]
sse.WriteJSON(list)
		select {
		case <-time.After(time.Second * 5):
		case <-sse.Done():
			return
		}
restful的这里建议NewTimer，确保超时内存能及时释放
		sse.WriteJSON(list)
		timeOut := time.NewTimer(time.Second * 5)
		defer timeOut.Stop()
		select {
		case <-timeOut.C:
		case <-sse.Done():
			return
		}
同样的server.go建议增加
	t := time.NewTicker(time.Duration(config.RemoveBanInterval) * time.Second)
	defer t.Stop() //新增

**Comment by langhuihui** [comment]
你可以直接提PR
