### ISSUE TITLE
接入 国标 配置好了 提示这个 gb28181 decode rtp error: size 481 < 49376: RTP header size insufficient for extension

### ISSUE THREAD

**Issue by tianzhike690** [Monibuca/plugin-gb28181#53]
接入 国标 配置好了 提示这个 gb28181 decode rtp error: size 481 < 49376: RTP header size insufficient for extension  什么问题啊

**Comment by sddnuaa** [comment]
我也遇到这个问题了，有解决？

**Comment by langhuihui** [comment]
可以按照B视频，dump下来给我吗？我可以重放来调试这个问题。https://www.bilibili.com/video/BV1TV4y1g7g6/

**Comment by langhuihui** [comment]
通常是由于发送的 rtp 包不完整导致后续解析错误，这个问题已经解决
