### ISSUE TITLE
海康摄像机使用gb28181报错

### ISSUE THREAD

**Issue by yuanshengpan** [Monibuca/plugin-gb28181#63]
panic: runtime error: slice bounds out of range [:-1]

goroutine 120 [running]:
m7s.live/plugin/gb28181/v4.(*GB28181Config).StoreDevice(0x1937440, {0xc000757645, 0x14}, {0x1235158, 0xc000c286e0}, 0xc00074d8e0)
	/home/runner/go/pkg/mod/m7s.live/plugin/gb28181/v4@v4.0.0-20220710074849-8f2a90e8ac40/device.go:88 +0x705
m7s.live/plugin/gb28181/v4.(*GB28181Config).OnRegister(0x1937440, {0x1235158?, 0xc000c286e0}, {0x7f635cf23318, 0xc000c07b80})
	/home/runner/go/pkg/mod/m7s.live/plugin/gb28181/v4@v4.0.0-20220710074849-8f2a90e8ac40/handle.go:95 +0x3f2
created by github.com/ghettovoice/gosip.(*server).handleRequest
	/home/runner/go/pkg/mod/github.com/ghettovoice/gosip@v0.0.0-20220420085539-cf932c28a8fe/server.go:270 +0x28a

**Comment by yuanshengpan** [comment]
![QQ截图20220715083435](https://user-images.githubusercontent.com/54977463/179123524-14e52edb-1fe0-4f4b-902e-6ac22a8c74b7.png)

摄像机配置，m7s默认配置

**Comment by moonxue** [comment]
这个bug我遇到过，改一下报错位置的代码就好了，最新的master好像已经修复了
