### ISSUE TITLE
关于设备注册的问题

### ISSUE THREAD

**Issue by myahuang** [Monibuca/plugin-gb28181#65]
按照GB28181附录J或者SIP协议，设备在SIP服务器注册成功，服务器返回的200相应中应该是有Contact这一头部字段的，但是目前版本插件是没有的，导致注册成功服务器返回给设备的报文是200 OK (0bingdings)，而正常的应该是200OK (1bingdings)，所以希望插件在返回的报文里添加Contact这一头部字段,这样就返回正确了

**Comment by langhuihui** [comment]
你可以帮忙提个 PR

**Comment by myahuang** [comment]
大佬您注意到然后版本跟新修改一下就可以了，我只是提醒一下。^_^
