### ISSUE TITLE
海康设备注册失败的问题

### ISSUE THREAD

**Issue by HaoqiLi025** [Monibuca/plugin-gb28181#66]
SIP服务器向设备发送inite请求，返回Status-Line: SIP/2.0 415 Unsupported Media Type。
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/29673415/185338267-e67873fb-8fcd-4733-a56d-75b93f5b9641.png">
<img width="788" alt="image" src="https://user-images.githubusercontent.com/29673415/185338373-a6b8d949-f3cf-4b85-9923-68805fc67f10.png">

**Comment by block1b** [comment]
sdp 最后加个空行即可

**Comment by langhuihui** [comment]
好的多谢
