### ISSUE TITLE
为什么我用VLC无法播放拉过来的视频流啊

### ISSUE THREAD

**Issue by myahuang** [Monibuca/plugin-gb28181#68]
大佬，我开启了rtsp插件和GB28181插件，使用http://[127.0.0.1:8080/api/summary?json=1](http://127.0.0.1:8080/api/summary?json=1)查询发现有视频流"Path":"34020000001110000001/34020000001320000002"的，但是播放rtsp://localhost/34020000001110000001/34020000001320000002却报错？

**Comment by langhuihui** [comment]
报什么错呢

**Comment by myahuang** [comment]
流媒体服务器没有报错，VLC播放器闪退，我用其他rtsp服务也是无法读取rtsp流，就是获取不到rtsp流，原来的hdl流也不能用rtsp流播放了，我仔细看看，应该不是GB28181插件的事

**Comment by myahuang** [comment]
![image](https://user-images.githubusercontent.com/57703532/190549633-8577b504-55db-4409-bcc5-fd08f5e478c1.png)
为什么monibuca会向NVR发送BYE 的SIP指令啊？我没添加任何指令啊，就是空引用插件

**Comment by myahuang** [comment]
下午我不用NVR了，直连IPC，VLC不会闪退，用http、rtmp、rtsp流播放画面均停滞，wirshark监测SIP报文正常，RTP报文不停的在传送。同时VLC播放hdl流正常，就是GB28181不行。
![image](https://user-images.githubusercontent.com/57703532/190579235-b05fb969-3840-4f77-b076-a76e83d22f79.png)

**Comment by langhuihui** [comment]
![1011663313296_ pic](https://user-images.githubusercontent.com/3647405/190581584-23f82f1b-b78c-4d04-9f18-8a820cf2ff14.jpg)
